"""initial migration

Revision ID: 371950a44837
Revises:
Create Date: 2024-12-08 20:36:35.795134

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "371950a44837"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("donations")
    # ### end Alembic commands ###
